project:
  type: book
  output-dir: docs
book:
  title: "Gut microbiome analysis for CRC detection: from raw sequences to machine learning models"
  author: "Pankaj Chejara"
  date: "11/28/2024"

  page-footer: "Copyright 2024, Pankaj Chejara"
  chapters:
    - index.qmd
    - part: ./chapters/16S/16S_processing_intro.qmd
      chapters:
        - ./chapters/16S/16S_chapter0.ipynb
        - ./chapters/16S/16S_chapter1.ipynb
        - ./chapters/16S/16S_chapter2.ipynb
        - ./chapters/16S/16S_chapter3.ipynb
        - ./chapters/16S/16S_chapter4.ipynb
        - ./chapters/16S/16S_chapter5.ipynb
    - part: ./chapters/Metagenomics/Meta_processing_intro.qmd
      chapters:
        - ./chapters/Metagenomics/Meta_chapter1.ipynb
        - ./chapters/Metagenomics/Meta_chapter2.ipynb
        - ./chapters/Metagenomics/Meta_chapter3.ipynb
        - ./chapters/Metagenomics/Meta_chapter4.ipynb
        - ./chapters/Metagenomics/Meta_chapter5.ipynb
    - part: ./chapters/Analysis/Analysis_intro.qmd
      chapters:
        - ./chapters/Analysis/chapter1.ipynb
        - ./chapters/Analysis/chapter2.ipynb
        - ./chapters/Analysis/chapter3.ipynb
        - ./chapters/Analysis/chapter4.ipynb
        - ./chapters/Analysis/chapter5.ipynb
        - ./chapters/Analysis/chapter6.ipynb
        - ./chapters/Analysis/generalizability.qmd

bibliography: references.bib

format:
  html:
    toc: true
    theme: cosmo


metadata:
 
  license: "Copyright @ Pankaj Chejara"